import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/database_service.dart';

class LocalizationProvider with ChangeNotifier {
  final DatabaseService _db = DatabaseService();
  String _localeCode = 'en';

  String get localeCode => _localeCode;
  bool get isSpanish => _localeCode == 'es';

  LocalizationProvider() {
    _loadLocale();
  }

  void _loadLocale() {
    _localeCode = _db.getPreferredLocale();
  }

  Future<void> setLocale(String langCode) async {
    if (langCode != 'en' && langCode != 'es') return;
    _localeCode = langCode;
    await _db.setPreferredLocale(langCode);
    notifyListeners();
  }

  String translate(String key, [List<String>? args]) {
    final dictionary = _localeCode == 'es' ? _es : _en;
    var val = dictionary[key] ?? key;
    if (args != null && args.isNotEmpty) {
      for (final arg in args) {
        val = val.replaceFirst('{}', arg);
      }
    }
    return val;
  }

  // --- ENGLISH DICTIONARY ---
  static const Map<String, String> _en = {
    'app_title': 'Flute Practice App',
    'app_subtitle': 'Your smart offline instrumental coach',
    'sign_in': 'Sign In',
    'sign_in_google': 'Sign in with Google',
    'or_practice_offline': 'OR PRACTICE OFFLINE',
    'your_name': 'Your Name',
    'practice_as_guest': 'Practice as Guest',
    'sign_out': 'Sign Out',
    'welcome_back': 'Welcome back,',
    'weekly_progress': 'Weekly Practice Progress',
    'minutes': 'minutes',
    'streak_days': '{} Days Current Streak',
    'current_streak_title': 'Current Streak',
    'total_sessions_title': 'Total Sessions',
    'exercises_done_title': 'Exercises Done',
    'total_study_time_title': 'Total Study Time',
    'days': 'Days',
    'update_goal_title': 'Update Weekly Practice Goal',
    'update_goal_desc': 'Define how many minutes you want to study per week. We will track your progress automatically.',
    'target_minutes': 'Target Minutes',
    'save': 'Save',
    'no_routines_configured': 'No routines configured yet.\nGo to the Routines tab to create one!',
    'technical_exercises_count': '{} technical exercises',
    'total_sessions': '{} Total Sessions',
    'exercises_done': '{} Exercises Done',
    'total_study_time': '{}m Total Study Time',
    'quick_start': 'Quick Start Routines',
    'free_study': 'Free Study',
    'dashboard_nav': 'Dashboard',
    'active_practice_session': 'Active Practice Session',
    'routine_label': 'Routine: {}',
    'free_study_piece': 'Free Study Piece',
    'routines': 'Routines',
    'repertoire': 'Repertoire',
    'history': 'History',
    // Active Practice View
    'free_repertoire_study': 'Free Repertoire Study',
    'study_clock_running': 'STUDY CLOCK RUNNING',
    'study_clock_paused': 'STUDY CLOCK PAUSED',
    'pause': 'Pause',
    'resume': 'Resume',
    'finish': 'Finish',
    'repertoire_tracking': 'Repertoire Active Piece Tracking',
    'repertoire_tracking_subtitle': 'Select the sheet music you are working on to accumulate time directly.',
    'none_technical_only': 'None (Technical Exercises Only)',
    'visual_metronome': 'Visual Metronome',
    'tempo': 'Tempo: {} BPM',
    'self_recorder': 'Self-Evaluation Recorder',
    'self_recorder_subtitle': 'Record a passage, play it back, and listen to your tone and articulation.',
    'open_self_recorder': 'Open Self-Recorder (Pauses Clock)',
    'close_recorder': 'Close Recorder & Resume Clock',
    'recording_paused': 'Recording Paused',
    'recording_stopped': 'Recording Stopped',
    'recording_playing': 'Playing Recording',
    'recording_active': 'RECORDING AUDIO...',
    'mic_error': 'Microphone permission not granted or recorder not initialized.',
    // Finish Dialog
    'finish_session_title': 'Finish Practice Session?',
    'finish_session_subtitle': 'Review your practice notes before saving. The session details and recordings will be logged to your history.',
    'practice_notes': 'Practice Notes',
    'keep_practicing': 'Keep Practicing',
    'save_finish': 'Save & Finish',
    'exit_practice_title': 'Exit Practice?',
    'exit_practice_desc': 'Do you want to discard your current progress or keep studying?',
    'discard_session_btn': 'Discard Session',
    'select_active_sheet': 'Select active sheet piece',
    'exercises_for_routine': 'Exercises for: {}',
    'recording_audio': 'Recording audio...',
    'recording_saved_temp': 'Practice Recording Saved (Local Temporary)',
    'mic_ready': 'Microphone Ready',
    // Routines View
    'routines_title': 'Technical Study Routines',
    'routines_subtitle': 'Structure your daily scale drills, long tones, and articulation guides.',
    'add_routine': 'Create Custom Routine',
    'routines_tab_title': 'Study Routines',
    'new_routine_title': 'New Study Routine',
    'create_btn': 'Create',
    'add_exercise_to': 'Add Exercise to {}',
    'target_bpm_tempo': 'Target BPM (Tempo)',
    'add_btn': 'Add',
    'no_routines_configured_empty': 'No study routines configured.',
    'click_add_routine': 'Click the "+" button in the top right to build your first technical routine.',
    'technical_exercises_default': 'Technical exercises',
    'technical_checklist': 'Technical Checklist',
    'no_exercises_added': 'No exercises added yet.',
    'exercise_detail_format': '{} • Target: {} BPM',
    'delete_routine_title': 'Delete Routine?',
    'delete_routine_confirm': 'Are you sure you want to delete "{}"? This cannot be undone.',
    'delete_btn': 'Delete',
    'routine_title_label': 'Routine Title',
    'routine_desc_label': 'Description',
    'exercises_list': 'Exercises',
    'add_exercise': 'Add Exercise',
    'exercise_name_label': 'Exercise Name',
    'articulation_label': 'Articulation',
    'target_bpm_label': 'Target BPM',
    'save_routine': 'Save Routine',
    'cancel': 'Cancel',
    // Repertoire View
    'repertoire_title': 'My Repertoire Binder',
    'repertoire_subtitle': 'Track your sheet music pieces, measure mastery, and metronome targets.',
    'add_piece': 'Add Repertoire Piece',
    'repertoire_manager_title': 'Repertoire Manager',
    'title_label': 'Title',
    'total_measures': 'Total Measures',
    'study_focus_notes': 'Study Focus Notes',
    'no_pdf_attached': 'No PDF sheet attached',
    'change_btn': 'Change',
    'browse_btn': 'Browse',
    'composer_format': 'Composer: {}',
    'target_tempo_format': 'Target Tempo: {} BPM',
    'score_sheet_format': 'Score sheet: {}',
    'measures_progress_format': 'Measures Progress: {} / {}',
    'focus_notes_label': 'Focus Notes:',
    'no_focus_notes': 'No focus notes written.',
    'save_progress_btn': 'Save Progress',
    'repertoire_empty_title': 'Your repertoire binder is empty.',
    'repertoire_empty_desc': 'Click the "+" button in the top right to catalog a musical piece and track your progress.',
    'unknown': 'Unknown',
    'meas_count_format': '{} / {} meas.',
    'piece_title_label': 'Piece Title',
    'composer_label': 'Composer',
    'measures_total': 'Total Measures',
    'measures_completed': 'Measures Completed',
    'study_notes': 'Study Notes',
    'save_piece': 'Save Piece',
    'progress_percent': '{}% completed',
    // History View
    'history_title': 'Practice Logs & Calendar',
    'history_subtitle': 'Track your dedication heat map and replay self-recorder sessions.',
    'session_details': 'Session Details',
    'no_sessions_day': 'No practice sessions recorded for this day.',
    'notes_label': 'Notes: {}',
    'duration_label': 'Duration: {} seconds',
    'play_recording_btn': 'Play Recording',
    'stop_playback_btn': 'Stop Playback',
    'practice_history_title': 'Practice History',
    'secs_format': '{} secs',
    'mins_format': '{} mins',
    'sessions_on_date': 'Sessions on {}',
    'recorded_count_format': '{} recorded',
    'no_sessions_on_day': 'No practice sessions recorded on this day.',
    'technical_exercises_completed_title': 'Technical Exercises Completed:',
    'repertoire_rehearsed_title': 'Repertoire Rehearsed:',
    'spent_duration': 'Spent: {}',
    'practice_session_notes_title': 'Practice Session Notes:',
    'recorded_self_evaluation_title': 'Recorded Self-Evaluation Snippet',
    'playing_back_audio': 'Playing back audio...',
    'audio_attached': 'Audio recording attached',
    // Notifications
    'session_saved': 'Practice session saved successfully!',
    'enter_valid_name': 'Please enter a valid name',
    'enter_title_desc': 'Please enter a title and description',
    'enter_piece_details': 'Please fill out all piece details',
    'weekly_goal_target': '{}% of your weekly target accomplished!',
  };

  // --- SPANISH DICTIONARY ---
  static const Map<String, String> _es = {
    'app_title': 'App de Práctica de Flauta',
    'app_subtitle': 'Tu entrenador instrumental inteligente offline',
    'sign_in': 'Iniciar Sesión',
    'sign_in_google': 'Iniciar sesión con Google',
    'or_practice_offline': 'O PRÁCTICA EN MODO OFFLINE',
    'your_name': 'Tu Nombre',
    'practice_as_guest': 'Practicar como Invitado',
    'sign_out': 'Cerrar Sesión',
    'welcome_back': 'Bienvenido de nuevo,',
    'weekly_progress': 'Progreso de Práctica Semanal',
    'minutes': 'minutos',
    'streak_days': '{} Días de Racha Actual',
    'current_streak_title': 'Racha Actual',
    'total_sessions_title': 'Sesiones Totales',
    'exercises_done_title': 'Ejercicios Realizados',
    'total_study_time_title': 'Tiempo de Estudio',
    'days': 'Días',
    'update_goal_title': 'Actualizar Meta Semanal',
    'update_goal_desc': 'Define cuántos minutos quieres estudiar por semana. Haremos un seguimiento automático.',
    'target_minutes': 'Minutos Objetivo',
    'save': 'Guardar',
    'no_routines_configured': 'Aún no hay rutinas configuradas.\n¡Ve a la pestaña de Rutinas para crear una!',
    'technical_exercises_count': '{} ejercicios técnicos',
    'total_sessions': '{} Sesiones Totales',
    'exercises_done': '{} Ejercicios Realizados',
    'total_study_time': '{}m de Tiempo de Estudio',
    'quick_start': 'Rutinas de Inicio Rápido',
    'free_study': 'Estudio Libre',
    'dashboard_nav': 'Inicio',
    'active_practice_session': 'Sesión de Práctica Activa',
    'routine_label': 'Rutina: {}',
    'free_study_piece': 'Pieza de Estudio Libre',
    'routines': 'Rutinas',
    'repertoire': 'Repertorio',
    'history': 'Historial',
    // Active Practice View
    'free_repertoire_study': 'Estudio Libre de Repertorio',
    'study_clock_running': 'RELOJ DE ESTUDIO CORRIENDO',
    'study_clock_paused': 'RELOJ DE ESTUDIO PAUSADO',
    'pause': 'Pausar',
    'resume': 'Reanudar',
    'finish': 'Terminar',
    'repertoire_tracking': 'Seguimiento de Pieza Activa de Repertorio',
    'repertoire_tracking_subtitle': 'Selecciona la partitura en la que estás trabajando para acumular tiempo directamente.',
    'none_technical_only': 'Ninguna (Solo Ejercicios Técnicos)',
    'visual_metronome': 'Metrónomo Visual',
    'tempo': 'Tempo: {} BPM',
    'self_recorder': 'Grabadora de Autoevaluación',
    'self_recorder_subtitle': 'Graba un fragmento, ejecútalo y escucha tu tono y articulación.',
    'open_self_recorder': 'Abrir Grabadora (Pausa el Reloj)',
    'close_recorder': 'Cerrar Grabadora y Reanudar Reloj',
    'recording_paused': 'Grabación Pausada',
    'recording_stopped': 'Grabación Detenida',
    'recording_playing': 'Reproduciendo Grabación',
    'recording_active': 'GRABANDO AUDIO...',
    'mic_error': 'Permiso de micrófono denegado o grabadora no inicializada.',
    // Finish Dialog
    'finish_session_title': '¿Terminar Sesión de Práctica?',
    'finish_session_subtitle': 'Revisa tus notas de práctica antes de guardar. Los detalles de la sesión y las grabaciones se guardarán en tu historial.',
    'practice_notes': 'Notas de Práctica',
    'keep_practicing': 'Seguir Practicando',
    'save_finish': 'Guardar y Finalizar',
    'exit_practice_title': '¿Salir de la Práctica?',
    'exit_practice_desc': '¿Deseas descartar tu progreso actual o seguir estudiando?',
    'discard_session_btn': 'Descartar Sesión',
    'select_active_sheet': 'Seleccionar partitura activa',
    'exercises_for_routine': 'Ejercicios para: {}',
    'recording_audio': 'Grabando audio...',
    'recording_saved_temp': 'Grabación Guardada (Temporal Local)',
    'mic_ready': 'Micrófono Listo',
    // Routines View
    'routines_title': 'Rutinas de Estudio Técnico',
    'routines_subtitle': 'Estructura tus ejercicios de respiración diarios, notas largas y guías de articulación.',
    'add_routine': 'Crear Rutina Personalizada',
    'routines_tab_title': 'Rutinas de Estudio',
    'new_routine_title': 'Nueva Rutina de Estudio',
    'create_btn': 'Crear',
    'add_exercise_to': 'Añadir Ejercicio a {}',
    'target_bpm_tempo': 'BPM Objetivo (Tempo)',
    'add_btn': 'Añadir',
    'no_routines_configured_empty': 'No hay rutinas de estudio configuradas.',
    'click_add_routine': 'Haz clic en el botón "+" en la parte superior derecha para crear tu primera rutina.',
    'technical_exercises_default': 'Ejercicios técnicos',
    'technical_checklist': 'Lista de Ejercicios',
    'no_exercises_added': 'Aún no se han añadido ejercicios.',
    'exercise_detail_format': '{} • Objetivo: {} BPM',
    'delete_routine_title': '¿Eliminar Rutina?',
    'delete_routine_confirm': '¿Estás seguro de que deseas eliminar "{}"? Esto no se puede deshacer.',
    'delete_btn': 'Eliminar',
    'routine_title_label': 'Título de la Rutina',
    'routine_desc_label': 'Descripción',
    'exercises_list': 'Ejercicios',
    'add_exercise': 'Añadir Ejercicio',
    'exercise_name_label': 'Nombre del Ejercicio',
    'articulation_label': 'Articulación',
    'target_bpm_label': 'BPM Objetivo',
    'save_routine': 'Guardar Rutina',
    'cancel': 'Cancelar',
    // Repertoire View
    'repertoire_title': 'Mi Carpeta de Repertorio',
    'repertoire_subtitle': 'Lleva un registro de tus partituras, compases dominados y tempos de metrónomo.',
    'add_piece': 'Añadir Pieza de Repertorio',
    'repertoire_manager_title': 'Gestor de Repertorio',
    'title_label': 'Título',
    'total_measures': 'Compases Totales',
    'study_focus_notes': 'Notas de Enfoque',
    'no_pdf_attached': 'Sin partitura PDF adjunta',
    'change_btn': 'Cambiar',
    'browse_btn': 'Buscar',
    'composer_format': 'Compositor: {}',
    'target_tempo_format': 'Tempo Objetivo: {} BPM',
    'score_sheet_format': 'Partitura: {}',
    'measures_progress_format': 'Progreso de Compases: {} / {}',
    'focus_notes_label': 'Notas de Enfoque:',
    'no_focus_notes': 'Sin notas de enfoque.',
    'save_progress_btn': 'Guardar Progreso',
    'repertoire_empty_title': 'Tu carpeta de repertorio está vacía.',
    'repertoire_empty_desc': 'Haz clic en el botón "+" en la parte superior derecha para catalogar una pieza musical y hacer un seguimiento de tu progreso.',
    'unknown': 'Desconocido',
    'meas_count_format': '{} / {} comp.',
    'piece_title_label': 'Título de la Pieza',
    'composer_label': 'Compositor',
    'measures_total': 'Compases Totales',
    'measures_completed': 'Compases Completados',
    'study_notes': 'Notas de Estudio',
    'save_piece': 'Guardar Pieza',
    'progress_percent': '{}% completado',
    // History View
    'history_title': 'Historial de Práctica y Calendario',
    'history_subtitle': 'Lleva un registro de tu mapa de calor de dedicación y reproduce grabaciones.',
    'session_details': 'Detalles de la Sesión',
    'no_sessions_day': 'No se registraron sesiones de práctica para este día.',
    'notes_label': 'Notas: {}',
    'duration_label': 'Duración: {} segundos',
    'play_recording_btn': 'Reproducir Grabación',
    'stop_playback_btn': 'Detener Reproducción',
    'practice_history_title': 'Historial de Práctica',
    'secs_format': '{} segs',
    'mins_format': '{} mins',
    'sessions_on_date': 'Sesiones el {}',
    'recorded_count_format': '{} registradas',
    'no_sessions_on_day': 'No se registraron sesiones de práctica en este día.',
    'technical_exercises_completed_title': 'Ejercicios Técnicos Completados:',
    'repertoire_rehearsed_title': 'Repertorio Ensayado:',
    'spent_duration': 'Tiempo: {}',
    'practice_session_notes_title': 'Notas de la Sesión de Práctica:',
    'recorded_self_evaluation_title': 'Fragmento de Autoevaluación Grabado',
    'playing_back_audio': 'Reproduciendo audio...',
    'audio_attached': 'Grabación de audio adjunta',
    // Notifications
    'session_saved': '¡Sesión de práctica guardada correctamente!',
    'enter_valid_name': 'Por favor ingresa un nombre válido',
    'enter_title_desc': 'Por favor ingresa un título y una descripción',
    'enter_piece_details': 'Por favor completa todos los detalles de la pieza',
    'weekly_goal_target': '¡{}% de tu objetivo semanal cumplido!',
  };
}

extension LocalizationExtension on BuildContext {
  String translate(String key, [List<String>? args]) {
    return Provider.of<LocalizationProvider>(this, listen: true).translate(key, args);
  }
}
